# **Feature Selection- Dropping constant features**

In this step we will be removing the features which have constant features(Values) which are actually not important for solving the problem statement.

In [1]:
# Import pandas to create DataFrame ...
import pandas as pd 
  
# Make DataFrame of the given data ...
data = pd.DataFrame({"A":[1,2,4,1,2,4], 
                    "B":[4,5,6,7,8,9], 
                    "C":[0,0,0,0,0,0],
                    "D":[1,1,1,1,1,1]})

In [2]:
data.head()
# Here Columns 'C' & 'D' have constant values, so we remove it, but we double check it using sklearn library ...

   A  B  C  D
0  1  4  0  1
1  2  5  0  1
2  4  6  0  1
3  1  7  0  1
4  2  8  0  1

**Variance Threshold** - **[Read More](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.VarianceThreshold.html)**

Feature selector that removes all low-variance features.

This feature selection algorithm looks only at the features (X), not the desired outputs (y), and can thus be used for unsupervised learning.

Constand features are of two types :
1. Constand Feature : Same value in all the records
2. Quasi Constand Feature : One of the value is dominant 99.9% in column.

In [3]:
### It will remove zero variance features ...
from sklearn.feature_selection import VarianceThreshold
var_thres = VarianceThreshold(threshold=0.0) # Change the threshold value : Quasi Constant...
var_thres.fit(data)

VarianceThreshold()

Use the **`get_constant_features`** functions to get all the constant features. : **[Read More](https://pypi.org/project/fast-ml/)**

# Code Snippet for both Constant & Quasi Constant features ...

from fast_ml.utilities import display_all
from fast_ml.feature_selection import get_constant_features

# Use the function to get the results in dataframe
constant_features = get_constant_features(df)
display_all(constant_features)

# All the constant features stored in a list
constant_features_list = constant_features['Var'].to_list()

# Drop all the constant features from the dataset
df.drop(columns = constant_features_list, inplace=True)

In [4]:
var_thres.get_support()
# Here the True values means they don't have zero varience and Flase have zero varience ...

array([ True,  True, False, False])

In [5]:
data.columns[var_thres.get_support()]

Index(['A', 'B'], dtype='object')

In [6]:
constant_columns = [column for column in data.columns
                    if column not in data.columns[var_thres.get_support()]]

print(len(constant_columns))

2

In [7]:
for feature in constant_columns:
     print(feature)

C
D

In [8]:
data.drop(constant_columns, axis=1)

   A  B
0  1  4
1  2  5
2  4  6
3  1  7
4  2  8
5  4  9

Lets practise on bigger dataset : **[Open Link](https://www.kaggle.com/c/santander-customer-satisfaction/data?select=train.csv)**

In [9]:
import pandas as pd
from sklearn.feature_selection import VarianceThreshold

In [10]:
df=pd.read_csv('santander.csv', nrows=10000)

In [11]:
df

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.00,0.00,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0
1,3,2,34,0.0,0.00,0.00,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0
2,4,2,23,0.0,0.00,0.00,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0
3,8,2,37,0.0,195.00,195.00,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0
4,10,2,39,0.0,0.00,0.00,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,20069,2,52,150.0,0.00,0.00,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27745.740000,1
9996,20070,2,23,90.0,51.06,51.06,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,120468.090000,0
9997,20071,2,37,0.0,0.00,0.00,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,98462.880000,0
9998,20072,2,24,0.0,0.00,0.00,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,102070.770000,0
9999,20074,2,40,585.0,0.00,0.00,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,55804.410000,0

In [12]:
X=df.drop(labels=['TARGET'], axis=1)
y=df['TARGET']

In [13]:
from sklearn.model_selection import train_test_split

# separate dataset into train and test ...
X_train, X_test, y_train, y_test = train_test_split(
    df.drop(labels=['TARGET'], axis=1),
    df['TARGET'],
    test_size=0.3,
    random_state=0)

X_train.shape, X_test.shape

((7000, 370), (3000, 370))

### Lets apply the variance threshold

In [14]:
var_thres=VarianceThreshold(threshold=0)
var_thres.fit(X_train)

VarianceThreshold(threshold=0)

In [15]:
var_thres.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True, False,  True, False, False,  True,
        True,  True,  True,  True, False, False,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True, False,  True, False,  True, False, False, False, False,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False,  True, False, False, False, False,  True,  True,
       False,  True, False, False, False,  True, False, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True, False, False, False,  True, False, False, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [16]:
# Finding non constant features ...
sum(var_thres.get_support())

284

In [17]:
# Lets Find non-constant features ...
len(X_train.columns[var_thres.get_support()])

284

In [18]:
constant_columns = [column for column in X_train.columns
                    if column not in X_train.columns[var_thres.get_support()]]

print(len(constant_columns))

86

In [19]:
for column in constant_columns:
    print(column)

ind_var2_0
ind_var2
ind_var13_medio_0
ind_var13_medio
ind_var18_0
ind_var18
ind_var27_0
ind_var28_0
ind_var28
ind_var27
ind_var34_0
ind_var34
ind_var41
ind_var46_0
ind_var46
num_var13_medio_0
num_var13_medio
num_var18_0
num_var18
num_var27_0
num_var28_0
num_var28
num_var27
num_var34_0
num_var34
num_var41
num_var46_0
num_var46
saldo_var13_medio
saldo_var18
saldo_var28
saldo_var27
saldo_var34
saldo_var41
saldo_var46
delta_imp_amort_var18_1y3
delta_imp_amort_var34_1y3
delta_imp_reemb_var17_1y3
delta_imp_reemb_var33_1y3
delta_imp_trasp_var17_out_1y3
delta_imp_trasp_var33_out_1y3
delta_num_reemb_var17_1y3
delta_num_reemb_var33_1y3
delta_num_trasp_var17_out_1y3
delta_num_trasp_var33_out_1y3
imp_amort_var18_hace3
imp_amort_var18_ult1
imp_amort_var34_hace3
imp_amort_var34_ult1
imp_var7_emit_ult1
imp_reemb_var13_hace3
imp_reemb_var17_hace3
imp_reemb_var17_ult1
imp_reemb_var33_hace3
imp_reemb_var33_ult1
imp_trasp_var17_in_hace3
imp_trasp_var17_out_hace3
imp_trasp_var17_out_ult1
imp_trasp_var33_in_hace3
imp_trasp_var33_out_hace3
imp_trasp_var33_out_ult1
imp_venta_var44_hace3
ind_var7_emit_ult1
num_var2_0_ult1
num_var2_ult1
num_var7_emit_ult1
num_meses_var13_medio_ult3
num_reemb_var13_hace3
num_reemb_var17_hace3
num_reemb_var17_ult1
num_reemb_var33_hace3
num_reemb_var33_ult1
num_trasp_var17_in_hace3
num_trasp_var17_out_hace3
num_trasp_var17_out_ult1
num_trasp_var33_in_hace3
num_trasp_var33_out_hace3
num_trasp_var33_out_ult1
num_venta_var44_hace3
saldo_var2_ult1
saldo_medio_var13_medio_hace2
saldo_medio_var13_medio_hace3
saldo_medio_var13_medio_ult1
saldo_medio_var13_medio_ult3
saldo_medio_var29_hace2
saldo_medio_var29_hace3

In [20]:
from fast_ml.utilities import display_all
from fast_ml.feature_selection import get_constant_features

# Use the function to get the results in dataframe
constant_features = get_constant_features(X_train)
display_all(constant_features)

# The top 86 is simple constant and rest are quasi constants ...

               Desc                            Var  Value        Perc
0          Constant      delta_imp_reemb_var17_1y3    0.0  100.000000
1          Constant          num_venta_var44_hace3    0.0  100.000000
2          Constant           num_reemb_var33_ult1    0.0  100.000000
3          Constant                    saldo_var46    0.0  100.000000
4          Constant                      num_var27    0.0  100.000000
5          Constant                      num_var28    0.0  100.000000
6          Constant                    num_var28_0    0.0  100.000000
7          Constant                    num_var27_0    0.0  100.000000
8          Constant                saldo_var2_ult1    0.0  100.000000
9          Constant  saldo_medio_var13_medio_hace2    0.0  100.000000
10         Constant      delta_imp_amort_var18_1y3    0.0  100.000000
11         Constant  saldo_medio_var13_medio_hace3    0.0  100.000000
12         Constant   saldo_medio_var13_medio_ult1    0.0  100.000000
13         Constant   saldo_medio_var13_medio_ult3    0.0  100.000000
14         Constant                      num_var18    0.0  100.000000
15         Constant                    num_var18_0    0.0  100.000000
16         Constant       imp_trasp_var33_in_hace3    0.0  100.000000
17         Constant      delta_imp_amort_var34_1y3    0.0  100.000000
18         Constant      imp_trasp_var33_out_hace3    0.0  100.000000
19         Constant                num_var13_medio    0.0  100.000000
20         Constant              num_var13_medio_0    0.0  100.000000
21         Constant                    saldo_var41    0.0  100.000000
22         Constant       imp_trasp_var17_out_ult1    0.0  100.000000
23         Constant       num_trasp_var17_in_hace3    0.0  100.000000
24         Constant      imp_trasp_var17_out_hace3    0.0  100.000000
25         Constant                    saldo_var28    0.0  100.000000
26         Constant          imp_reemb_var33_hace3    0.0  100.000000
27         Constant                    saldo_var18    0.0  100.000000
28         Constant           imp_reemb_var33_ult1    0.0  100.000000
29         Constant      num_trasp_var17_out_hace3    0.0  100.000000
30         Constant              saldo_var13_medio    0.0  100.000000
31         Constant           imp_reemb_var17_ult1    0.0  100.000000
32         Constant       num_trasp_var17_out_ult1    0.0  100.000000
33         Constant                      num_var46    0.0  100.000000
34         Constant                    num_var46_0    0.0  100.000000
35         Constant       num_trasp_var33_in_hace3    0.0  100.000000
36         Constant                    saldo_var34    0.0  100.000000
37         Constant      num_trasp_var33_out_hace3    0.0  100.000000
38         Constant                      num_var41    0.0  100.000000
39         Constant       num_trasp_var33_out_ult1    0.0  100.000000
40         Constant                      num_var34    0.0  100.000000
41         Constant                    num_var34_0    0.0  100.000000
42         Constant       imp_trasp_var17_in_hace3    0.0  100.000000
43         Constant          imp_reemb_var17_hace3    0.0  100.000000
44         Constant          imp_reemb_var13_hace3    0.0  100.000000
45         Constant                    saldo_var27    0.0  100.000000
46         Constant      delta_imp_reemb_var33_1y3    0.0  100.000000
47         Constant              ind_var13_medio_0    0.0  100.000000
48         Constant                    ind_var27_0    0.0  100.000000
49         Constant          num_reemb_var13_hace3    0.0  100.000000
50         Constant  delta_num_trasp_var17_out_1y3    0.0  100.000000
51         Constant                      ind_var18    0.0  100.000000
52         Constant                    ind_var18_0    0.0  100.000000
53         Constant  delta_num_trasp_var33_out_1y3    0.0  100.000000
54         Constant             num_var7_emit_ult1    0.0  100.000000
55         Constant                ind_var13_medio    0.0  100.000000
56         Constant          imp_amort_var18_hace3    0.0  100.000000
57         Constant                      ind_var28    0.0  100.000000
58         Constant           imp_amort_var18_ult1    0.0  100.000000
59         Constant                       ind_var2    0.0  100.000000
60         Constant                     ind_var2_0    0.0  100.000000
61         Constant          imp_amort_var34_hace3    0.0  100.000000
62         Constant           imp_amort_var34_ult1    0.0  100.000000
63         Constant           num_reemb_var17_ult1    0.0  100.000000
64         Constant     num_meses_var13_medio_ult3    0.0  100.000000
65         Constant             imp_var7_emit_ult1    0.0  100.000000
66         Constant                      ind_var46    0.0  100.000000
67         Constant                    ind_var28_0    0.0  100.000000
68         Constant                      ind_var27    0.0  100.000000
69         Constant      delta_num_reemb_var33_1y3    0.0  100.000000
70         Constant                    ind_var46_0    0.0  100.000000
71         Constant       imp_trasp_var33_out_ult1    0.0  100.000000
72         Constant          imp_venta_var44_hace3    0.0  100.000000
73         Constant        saldo_medio_var29_hace2    0.0  100.000000
74         Constant                      ind_var41    0.0  100.000000
75         Constant        saldo_medio_var29_hace3    0.0  100.000000
76         Constant                      ind_var34    0.0  100.000000
77         Constant                    ind_var34_0    0.0  100.000000
78         Constant             ind_var7_emit_ult1    0.0  100.000000
79         Constant  delta_imp_trasp_var17_out_1y3    0.0  100.000000
80         Constant                num_var2_0_ult1    0.0  100.000000
81         Constant                  num_var2_ult1    0.0  100.000000
82         Constant          num_reemb_var33_hace3    0.0  100.000000
83         Constant  delta_imp_trasp_var33_out_1y3    0.0  100.000000
84         Constant          num_reemb_var17_hace3    0.0  100.000000
85         Constant      delta_num_reemb_var17_1y3    0.0  100.000000
86   Quasi Constant   delta_imp_trasp_var17_in_1y3    0.0   99.985714
87   Quasi Constant   delta_num_trasp_var33_in_1y3    0.0   99.985714
88   Quasi Constant   delta_num_trasp_var17_in_1y3    0.0   99.985714
89   Quasi Constant   delta_imp_trasp_var33_in_1y3    0.0   99.985714
90   Quasi Constant                      num_var29    0.0   99.985714
91   Quasi Constant                    saldo_var29    0.0   99.985714
92   Quasi Constant                       num_var6    0.0   99.985714
93   Quasi Constant                      ind_var29    0.0   99.985714
94   Quasi Constant           num_aport_var33_ult1    0.0   99.985714
95   Quasi Constant        num_trasp_var17_in_ult1    0.0   99.985714
96   Quasi Constant         saldo_medio_var29_ult3    0.0   99.985714
97   Quasi Constant         saldo_medio_var29_ult1    0.0   99.985714
98   Quasi Constant                       ind_var6    0.0   99.985714
99   Quasi Constant                     ind_var6_0    0.0   99.985714
100  Quasi Constant        saldo_medio_var17_hace3    0.0   99.985714
101  Quasi Constant                     num_var6_0    0.0   99.985714
102  Quasi Constant                    ind_var29_0    0.0   99.985714
103  Quasi Constant        imp_trasp_var33_in_ult1    0.0   99.985714
104  Quasi Constant             num_op_var40_hace3    0.0   99.985714
105  Quasi Constant                    num_var29_0    0.0   99.985714
106  Quasi Constant           imp_aport_var33_ult1    0.0   99.985714
107  Quasi Constant           num_meses_var29_ult3    0.0   99.985714
108  Quasi Constant        imp_trasp_var17_in_ult1    0.0   99.985714
109  Quasi Constant        num_trasp_var33_in_ult1    0.0   99.985714
110  Quasi Constant                     saldo_var6    0.0   99.985714
111  Quasi Constant          imp_aport_var17_hace3    0.0   99.971429
112  Quasi Constant          num_aport_var17_hace3    0.0   99.971429
113  Quasi Constant         num_compra_var44_hace3    0.0   99.957143
114  Quasi Constant        saldo_medio_var33_hace3    0.0   99.957143
115  Quasi Constant      delta_num_venta_var44_1y3    0.0   99.957143
116  Quasi Constant          num_aport_var33_hace3    0.0   99.957143
117  Quasi Constant        saldo_medio_var44_hace3    0.0   99.957143
118  Quasi Constant      delta_imp_venta_var44_1y3    0.0   99.957143
119  Quasi Constant      delta_num_reemb_var13_1y3    0.0   99.957143
120  Quasi Constant        saldo_medio_var33_hace2    0.0   99.957143
121  Quasi Constant      delta_num_aport_var33_1y3    0.0   99.957143
122  Quasi Constant         imp_compra_var44_hace3    0.0   99.957143
123  Quasi Constant           num_reemb_var13_ult1    0.0   99.957143
124  Quasi Constant           imp_venta_var44_ult1    0.0   99.957143
125  Quasi Constant      delta_imp_reemb_var13_1y3    0.0   99.957143
126  Quasi Constant      delta_imp_aport_var33_1y3    0.0   99.957143
127  Quasi Constant           imp_reemb_var13_ult1    0.0   99.957143
128  Quasi Constant           num_venta_var44_ult1    0.0   99.957143
129  Quasi Constant          imp_aport_var33_hace3    0.0   99.957143
130  Quasi Constant        num_op_var40_efect_ult1    0.0   99.942857
131  Quasi Constant           num_meses_var33_ult3    0.0   99.942857
132  Quasi Constant                      ind_var33    0.0   99.942857
133  Quasi Constant        imp_op_var40_efect_ult1    0.0   99.942857
134  Quasi Constant             imp_sal_var16_ult1    0.0   99.942857
135  Quasi Constant             num_sal_var16_ult1    0.0   99.942857
136  Quasi Constant                    saldo_var33    0.0   99.942857
137  Quasi Constant         saldo_medio_var33_ult3    0.0   99.942857
138  Quasi Constant                      num_var33    0.0   99.942857
139  Quasi Constant         saldo_medio_var33_ult1    0.0   99.942857
140  Quasi Constant        saldo_medio_var17_hace2    0.0   99.928571
141  Quasi Constant        imp_op_var40_efect_ult3    0.0   99.928571
142  Quasi Constant        num_op_var40_efect_ult3    0.0   99.928571
143  Quasi Constant           num_aport_var17_ult1    0.0   99.928571
144  Quasi Constant                    ind_var33_0    0.0   99.928571
145  Quasi Constant           imp_aport_var17_ult1    0.0   99.928571
146  Quasi Constant                    num_var33_0    0.0   99.928571
147  Quasi Constant                    saldo_var32    0.0   99.914286
148  Quasi Constant                    num_var32_0    0.0   99.914286
149  Quasi Constant                      num_var32    0.0   99.914286
150  Quasi Constant                      ind_var32    0.0   99.914286
151  Quasi Constant                    ind_var32_0    0.0   99.914286
152  Quasi Constant      delta_num_aport_var17_1y3    0.0   99.900000
153  Quasi Constant                  ind_var32_cte    0.0   99.900000
154  Quasi Constant      delta_imp_aport_var17_1y3    0.0   99.900000
155  Quasi Constant                      ind_var17    0.0   99.885714
156  Quasi Constant          imp_compra_var44_ult1    0.0   99.885714
157  Quasi Constant          num_compra_var44_ult1    0.0   99.885714
158  Quasi Constant                      num_var17    0.0   99.885714
159  Quasi Constant         saldo_medio_var17_ult3    0.0   99.885714
160  Quasi Constant         saldo_medio_var17_ult1    0.0   99.885714
161  Quasi Constant                    saldo_var17    0.0   99.885714
162  Quasi Constant        saldo_medio_var44_hace2    0.0   99.871429
163  Quasi Constant           num_meses_var17_ult3    0.0   99.871429
164  Quasi Constant     delta_imp_compra_var44_1y3    0.0   99.857143
165  Quasi Constant     delta_num_compra_var44_1y3    0.0   99.857143
166  Quasi Constant                    num_var17_0    0.0   99.842857
167  Quasi Constant                    ind_var17_0    0.0   99.842857
168  Quasi Constant           num_meses_var44_ult3    0.0   99.828571
169  Quasi Constant         saldo_medio_var44_ult1    0.0   99.828571
170  Quasi Constant         saldo_medio_var44_ult3    0.0   99.828571
171  Quasi Constant                    ind_var44_0    0.0   99.828571
172  Quasi Constant                      num_var44    0.0   99.828571
173  Quasi Constant                      ind_var44    0.0   99.828571
174  Quasi Constant                    saldo_var44    0.0   99.828571
175  Quasi Constant                    num_var44_0    0.0   99.828571
176  Quasi Constant             num_op_var40_hace2    0.0   99.814286
177  Quasi Constant            num_var7_recib_ult1    0.0   99.814286
178  Quasi Constant            ind_var7_recib_ult1    0.0   99.814286
179  Quasi Constant            imp_var7_recib_ult1    0.0   99.814286
180  Quasi Constant                      ind_var20    0.0   99.742857
181  Quasi Constant                      num_var20    0.0   99.742857
182  Quasi Constant                    saldo_var20    0.0   99.742857
183  Quasi Constant                    ind_var20_0    0.0   99.685714
184  Quasi Constant                    num_var20_0    0.0   99.685714
185  Quasi Constant                      num_var31    0.0   99.657143
186  Quasi Constant                      ind_var31    0.0   99.657143
187  Quasi Constant                    saldo_var31    0.0   99.657143
188  Quasi Constant                    num_var31_0    0.0   99.614286
189  Quasi Constant                    ind_var31_0    0.0   99.614286
190  Quasi Constant                      ind_var19    0.0   99.600000
191  Quasi Constant              num_op_var40_ult1    0.0   99.557143
192  Quasi Constant              num_op_var40_ult3    0.0   99.557143
193  Quasi Constant              imp_op_var40_ult1    0.0   99.557143
194  Quasi Constant           imp_aport_var13_ult1    0.0   99.514286
195  Quasi Constant           num_aport_var13_ult1    0.0   99.514286
196  Quasi Constant                      ind_var40    0.0   99.500000
197  Quasi Constant                       num_var1    0.0   99.500000
198  Quasi Constant                      num_var39    0.0   99.500000
199  Quasi Constant                      num_var40    0.0   99.500000
200  Quasi Constant                      ind_var39    0.0   99.500000
201  Quasi Constant                     saldo_var1    0.0   99.500000
202  Quasi Constant                    saldo_var40    0.0   99.500000
203  Quasi Constant                       ind_var1    0.0   99.500000
204  Quasi Constant                    ind_var30_0    1.0   99.457143
205  Quasi Constant        num_op_var40_comer_ult1    0.0   99.428571
206  Quasi Constant        imp_op_var40_comer_ult1    0.0   99.428571
207  Quasi Constant         saldo_medio_var8_hace3    0.0   99.414286
208  Quasi Constant                      num_var14    0.0   99.400000
209  Quasi Constant                    saldo_var14    0.0   99.400000
210  Quasi Constant                      ind_var14    0.0   99.400000
211  Quasi Constant  saldo_medio_var13_largo_hace3    0.0   99.385714
212  Quasi Constant        num_op_var40_comer_ult3    0.0   99.328571
213  Quasi Constant        imp_op_var40_comer_ult3    0.0   99.328571
214  Quasi Constant  saldo_medio_var13_largo_hace2    0.0   99.114286
215  Quasi Constant   saldo_medio_var13_largo_ult3    0.0   99.071429
216  Quasi Constant   saldo_medio_var13_largo_ult1    0.0   99.071429
217  Quasi Constant     num_meses_var13_largo_ult3    0.0   99.042857

In [21]:
# Drop all the constant & Quasi constant features from the dataset ...
df.drop(columns = constant_features['Var'], inplace=True)

In [22]:
df

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var41_comer_ult1,imp_op_var41_comer_ult3,imp_op_var41_efect_ult1,imp_op_var41_efect_ult3,...,saldo_medio_var12_hace2,saldo_medio_var12_hace3,saldo_medio_var12_ult1,saldo_medio_var12_ult3,saldo_medio_var13_corto_hace2,saldo_medio_var13_corto_hace3,saldo_medio_var13_corto_ult1,saldo_medio_var13_corto_ult3,var38,TARGET
0,1,2,23,0.0,0.00,0.00,0.00,0.00,0.0,0.0,...,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,39205.170000,0
1,3,2,34,0.0,0.00,0.00,0.00,0.00,0.0,0.0,...,0.0,0.0,0.00,0.00,300.0,122.22,300.0,240.75,49278.030000,0
2,4,2,23,0.0,0.00,0.00,0.00,0.00,0.0,0.0,...,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,67333.770000,0
3,8,2,37,0.0,195.00,195.00,195.00,195.00,0.0,0.0,...,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,64007.970000,0
4,10,2,39,0.0,0.00,0.00,0.00,0.00,0.0,0.0,...,0.0,0.0,85501.89,85501.89,0.0,0.00,0.0,0.00,117310.979016,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,20069,2,52,150.0,0.00,0.00,0.00,0.00,0.0,0.0,...,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,27745.740000,1
9996,20070,2,23,90.0,51.06,51.06,51.06,51.06,0.0,0.0,...,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,120468.090000,0
9997,20071,2,37,0.0,0.00,0.00,0.00,0.00,0.0,0.0,...,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,98462.880000,0
9998,20072,2,24,0.0,0.00,0.00,0.00,0.00,0.0,0.0,...,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,102070.770000,0
9999,20074,2,40,585.0,0.00,0.00,0.00,0.00,0.0,0.0,...,0.0,0.0,0.00,0.00,18000.0,5400.03,18000.0,13800.00,55804.410000,0

In [23]:
# Done ...